version: "3.9"
services:
  rtmp:
    image: "bre1010/streaming_monitor:test"
    build: ./rtmp
    ports:
      - "1935:1935"
      - "80:8080"
    container_name: rtmp_server
    volumes:
      - ./data:/tmp/hls

  auth:
    build: ./auth
    container_name: auth_server

  collab:
    build: ./collab
    container_name: collab_server
